[deploy]
rabbit_ini    = testRabbitMQ.ini
deploy_queue  = deployServer

[bundle]
name        = ui-title
description = "Fix <title> in Home page"

;files that were edited or need to be bundled
file = /var/www/html/home.php

;systemd services to bounce
service.1 = apache2
