[deploy]
rabbit_ini    = testRabbitMQ.ini
deploy_queue  = deployServer

[bundle]
name        = fixBuginBackEnd

;files that were edited or need to be bundled
file1 = /home/vboxuser/git/it490-Final-Submission/dbListener.php
file2 = /home/vboxuser/git/it490-Final-Submission/getInfo.ini

;systemd services to bounce
service.1 = rabbitmq
command1 = "echo 'hello from config'"
