[deploy]
rabbit_ini    = testRabbitMQ.ini
deploy_queue  = deployServer

[bundle]
name        = fixBuginBackEnd
description = "changed one thing"

;files that were edited or need to be bundled
file = /home/vboxuser/git/it490-Final-Submission/dbListener.php

;systemd services to bounce
service.1 = rabbitmq
