
[deployServer]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
QUEUE = deployQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

; ========= QA QUEUES (consumers on QA VMs) =========
[QA_Webserver]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
;EXCHANGE_TYPE = ????
QUEUE = QA_Webserver
AUTO_DELETE = false

[QA_Backend]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
;EXCHANGE_TYPE = ????
QUEUE = QA_Backend
AUTO_DELETE = false

[QA_DMZ]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
;EXCHANGE_TYPE = ????
QUEUE = QA_DMZ
AUTO_DELETE = false

; ========= PROD QUEUES (consumers on PROD VMs) =========
[PROD_Webserver]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
;EXCHANGE_TYPE = ????
QUEUE = PROD_Webserver
AUTO_DELETE = false

[PROD_Backend]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
;EXCHANGE_TYPE = ????
QUEUE = PROD_Backend
AUTO_DELETE = false

[PROD_DMZ]
BROKER_HOST = 127.0.0.1
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
;EXCHANGE_TYPE = ????
QUEUE = PROD_DMZ
AUTO_DELETE = false

