[dmzServer]
BROKER_HOST = 100.80.184.27
BROKER_PORT = 5672
USER        = dmzUser
PASSWORD    = dmzPass123
VHOST       = dmzHost
EXCHANGE    = dmzExchange
QUEUE       = dmzQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

<<<<<<< HEAD
[deployServer]
BROKER_HOST = 100.76.145.42
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
QUEUE = deployQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[QA_DMZ]
BROKER_HOST = 100.76.145.42
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
EXCHANGE_TYPE = direct
QUEUE = QA_DMZ
AUTO_DELETE = true

[PROD_DMZ]
BROKER_HOST = 100.76.145.42
BROKER_PORT = 5672
USER = deployUser
PASSWORD = deploy123
VHOST = deployHost
EXCHANGE = deployExchange
EXCHANGE_TYPE = direct
QUEUE = PROD_DMZ
=======
[logServerWeb]
BROKER_HOST = 100.89.10.38
BROKER_PORT = 5672
USER = logUser
PASSWORD = logPass123
VHOST = logHost
EXCHANGE = logExchange
QUEUE = webQueue
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[logServerDB]
BROKER_HOST = 100.89.10.38
BROKER_PORT = 5672
USER = logUser
PASSWORD = logPass123
VHOST = logHost
EXCHANGE = logExchange
QUEUE = dbRabbitQueue
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[logServerDMZ]
BROKER_HOST = 100.89.10.38
BROKER_PORT = 5672
USER = logUser
PASSWORD = logPass123
VHOST = logHost
EXCHANGE = logExchange
QUEUE = logQueue
EXCHANGE_TYPE = fanout
>>>>>>> b4010c1935b83b3e3c8a176304f245bb3ae86c27
AUTO_DELETE = true