[dmzServer]
BROKER_HOST = 100.80.184.27
BROKER_PORT = 5672
USER        = dmzUser
PASSWORD    = dmzPass123
VHOST       = dmzHost
EXCHANGE    = dmzExchange
QUEUE       = dmzQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

[logServerWeb]
BROKER_HOST = 100.89.10.38
BROKER_PORT = 5672
USER = logUser
PASSWORD = logPass123
VHOST = logHost
EXCHANGE = logExchange
QUEUE = webQueue
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[logServerDB]
BROKER_HOST = 100.89.10.38
BROKER_PORT = 5672
USER = logUser
PASSWORD = logPass123
VHOST = logHost
EXCHANGE = logExchange
QUEUE = dbRabbitQueue
EXCHANGE_TYPE = fanout
AUTO_DELETE = true

[logServerDMZ]
BROKER_HOST = 100.89.10.38
BROKER_PORT = 5672
USER = logUser
PASSWORD = logPass123
VHOST = logHost
EXCHANGE = logExchange
QUEUE = logQueue
EXCHANGE_TYPE = fanout
AUTO_DELETE = true